<!DOCTYPE html>
<html>
	<head>
		<title>Redirecting...</title>
		<meta http-equiv="refresh" content="0;url=https://www.garmix.yaroslav-kozak.com/garmix.yaroslav-kozak.com">
	</head>
	<body>
		<script type="text/javascript">
			window.location = "https://www.garmix.yaroslav-kozak.com/garmix.yaroslav-kozak.com";
		</script>

		<p>You are being redirected to <a href="https://www.garmix.yaroslav-kozak.com/garmix.yaroslav-kozak.com">https://www.garmix.yaroslav-kozak.com/garmix.yaroslav-kozak.com</a></p>
	</body>
</html>
